config/routes.rb
Rails.application.routes.draw do

  # display a list of all machines
  get '/machines', to: 'machines#index', as: 'machines'

  # go to a form to create a new machine
  get '/machines/new', to: 'machines#new', as: 'new_machine'
  post '/machines', to: 'machines#create'

  # go to a form to edit a machine
  get '/machines/:id/edit', to: 'machines#edit', as: 'edit_machine'
  patch '/machines/:id', to: 'machines#update'

  # delete a particular machine
  get '/machines/:id/destroy', to: 'machines#destroy', as: 'delete_machine'

  # display a particular machine
  get '/machines/:id', to: 'machines#show', as: 'machine'

  # get '', to: '', as: ''

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord

    def to_s
        "#{ self.brand } #{ self.model }"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  
  def index
    @all_machines = Machine.all
  end

  def show
    @this_machine = Machine.find( params[ :id ] )
  end

  def new
    @new_machine = Machine.new
  end

  def create
    new_machine = Machine.create( brand: params[ :machine ][ :brand ], model: params[ :machine ][ :model ], bobbin: params[ :machine ][ :bobbin ], needle: params[ :machine ][ :needle ] )
    redirect_to machine_path( new_machine )
  end

  def edit
    @machine_to_edit = Machine.find( params[ :id ] )
  end

  def update
    @machine = Machine.find( params[ :id ] )
    @machine.update( machine_params )
    redirect_to machine_path( @machine )
  end

  def destroy
    Machine.destroy( params[ :id ] )
    redirect_to machines_path
  end

  private

  def machine_params
    params.require( :machine ).permit( :brand, :model, :bobbin, :needle )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSewingMachineStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/edit.html.erb
<h1><%= "Edit machine: #{ @machine_to_edit.to_s }" %></h1>

<%= form_for @machine_to_edit do | f | %>
    <%= label_tag "Edit brand:" %>
    <%= f.text_field :brand %><br /><br />

    <%= label_tag "Edit model:" %>
    <%= f.text_field :model %><br /><br />

    <%= label_tag "Edit bobbin class:" %>
    <%= f.text_field :bobbin %><br /><br />

    <%= label_tag "Edit needle size:" %>
    <%= f.text_field :needle %><br /><br />
    
    <%= f.submit "Edit this machine" %>
<% end %>

app/views/machines/index.html.erb
<h1>View all machines</h1>

<ul>
    <% @all_machines.each do | machine | %>
        <li>
            <%= link_to "#{ machine }", machine_path( machine ) %> | <%= link_to "Edit", edit_machine_path( machine ) %> | <%= link_to "Delete", delete_machine_path( machine ) %>
        </li>
    <% end %>
</ul>
<%= link_to "New machine", new_machine_path %>

app/views/machines/new.html.erb
<h1>Create a new machine</h1>

<%= form_for @new_machine do | f | %>
    <%= label_tag "Brand:" %>
    <%= f.text_field :brand %><br /><br />

    <%= label_tag "Model:" %>
    <%= f.text_field :model %><br /><br />

    <%= label_tag "Bobbin class:" %>
    <%= f.text_field :bobbin %><br /><br />

    <%= label_tag "Needle size:" %>
    <%= f.text_field :needle %><br /><br />
    
    <%= f.submit "Create machine" %>
<% end %>

app/views/machines/show.html.erb
<h1><%= "Machine details: #{ @this_machine.to_s }" %></h1>
<ul>
    <li><%= "Bobbin class: #{ @this_machine.bobbin }" %></li>
    <li><%= "Needle style: #{ @this_machine.needle }" %></li>
</ul>
<%= link_to "Delete this machine", delete_machine_path( @this_machine ) %> | <%= link_to "View all machines", machines_path %>